version: '3.8'
services:

  # Users service
  users-service:
    build: .  # Собираем из Dockerfile в текущей папке
    container_name: users-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres  # Имя сервиса из этого же compose файла
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8081:8080"  # Открываем порт для доступа извне
    depends_on:
      postgres:  # Сначала запускаем postgres
        condition: service_healthy
    networks:
      - users-network

  postgres:
    image: postgres:16
    container_name: users-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - users-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  users-network:
    driver: bridge