apiVersion: v2
name: users-service
description: Users Service Helm Chart
version: 0.0.3
appVersion: "0.0.3"
dependencies:
  - name: postgresql
#        https://app-catalog.vmware.com/bitnami/releases/a5f09427-0f05-450f-b416-6d6824a4748a
    version: "18.1.10"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: ingress-nginx
    version: "4.12.8"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
#      https://github.com/kubernetes/ingress-nginx