# values.yaml для PostgreSQL (bitnami/postgresql)
#image:
#  tag: "16"

auth:
  enablePostgresPasswordRotation: false
  username: app_user
  existingSecret: db-secret
  existingSecretPasswordKey: password
  database: usersdb
  createSecret: false
  enablePostgresUser: true

primary:
#  initdbScripts:
#    init-user-db.sql: |
#      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
#      -- Дополнительные настройки при необходимости

#  resources:
#    requests:
#      memory: 256Mi
#      cpu: 100m
#    limits:
#      memory: 512Mi
#      cpu: 200m

  service:
    type: ClusterIP
    port: 5432

  persistence:
    enabled: true
    size: 2Gi
    storageClass: standard

architecture: "standalone"