apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    # app: {{ .Values.app.name }}
    {{- include "app.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      # app: {{ .Values.app.name }}
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      # serviceAccountName: {{ .Release.Name }}-deps-checker  # ServiceAccount
#---    
      initContainers:
        {{- if .Values.database.migration.enabled }}
        - name: wait-for-migration
          image: postgres:15-alpine # 
          command:                                # wait for postgres
            - sh
            - -c
            - |            
              echo "Checking PostgreSQL availability..."
              until pg_isready -h {{ .Release.Name }}-postgresql -p 5432 -U app_user -d usersdb -t 30; do
                echo "PostgreSQL not ready, waiting..."
                sleep 2
              done
              echo "PostgreSQL is ready"
        {{- end }}     
#---
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.profiles | default "kubernetes" }}
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.passwordKey }}
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/app/config/
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.liveness.delay }}
            periodSeconds: 10
            timeoutSeconds: {{ .Values.liveness.timeout }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.app.name }}-config
            items:
              - key: application-kubernetes.yaml
                path: application-kubernetes.yaml