apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-deps-checker  # ServiceAccount
      initContainers:
        {{- if .Values.database.migration.enabled }}
        - name: wait-for-migration
          image: registry.k8s.io/kubectl:v1.29.0  # Kubernetes image
          command:                                # wait for job is finished. could it lead to a circular dependency job-deploy?
              - kubectl
              - wait
              - --for=condition=complete
              - job/{{ .Release.Name }}-db-migrate
              - --timeout={{ .Values.database.migration.timeout }}s 
        {{- end }}     
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.profiles | default "kubernetes" }}
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.passwordKey }}
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/app/config/
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.liveness.delay }}
            periodSeconds: 10
            timeoutSeconds: {{ .Values.liveness.timeout }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.app.name }}-config
            items:
              - key: application-kubernetes.yaml
                path: application-kubernetes.yaml